version: '3'

services:
  neo4j:
    image: neo4j:enterprise
    container_name: permits_neo4j
    volumes:
      - ./data/neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/docker-graph

  api:
    build: ./api
    container_name: permits_api
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=docker-graph
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql

    links:
      - neo4j
    depends_on:
      - neo4j

  ui:
    build: ./client
    container_name: permits_ui
    volumes:
      - './client:/app'
      - './client/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CI=true
      - REACT_APP_GRAPHQL_URI=http://localhost:4001/graphql
      - PROXY=http://api:4001/graphql
    links:
      - api
    depends_on:
      - api
